credential:
  access_key: "access_key"
  secret_key: "secret_key"
  region: "region"

rate_limit: 15                #云监控拉数据接口最大限制, 20/秒, 1200/分钟, https://cloud.tencent.com/document/product/248/31014

products:
  - namespace: QCE/LB_PRIVATE    #指标详情: https://cloud.tencent.com/document/product/248/51899
    all_metrics: true
    all_instances: true
    #only_include_metrics:
    #  - CpuUseRate
    #  - ClientInactiveConn
    #  - ClientConcurConn
    #  - ClientNewConn
    #  - ClientInpkg
    #  - ClientOutpkg
    #  - ClientAccIntraffic
    #  - ClientAccOuttraffic
    #  - ClientIntraffic
    #  - ClientOuttraffic
    #  - UnhealthRsCount
    #  - RspTimeout
    #  - RspAvg
    #  - InDropPkts
    #  - OutDropPkts
    #  - Http2xx
    #  - Http3xx
    #  - Http4xx
    #  - Http5xx
    #  - TotalReq
    #  - DropTotalConns 
    #only_include_metrics: []
    #only_include_instances: [lb-xxxxxxxx]
    #extra_labels: [LoadBalancerName, LoadBalancerId,LoadBalancerType, LoadBalancerVips, ProjectId,Tags]
    #statistics_types: [last]
    #period_seconds: 60
    #metric_name_type: 2